name: WoolWars
main: VaxPex\WoolWars
src-namespace-prefix: VaxPex
version: 1.0.0
api: [4.0.0]
author: VaxPex
description: WoolWars

permissions:
  ws.admin:
    description: all the permissions of woolwars
    default: op
